apiVersion: v1
kind: Service
metadata:
  name: ecommerce-workshop
  namespace: workshop
  labels:
    app: ecommerce-workshop
spec:
  type: ClusterIP
  selector:
    app: ecommerce-workshop
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
